### ISSUE TITLE
Crash When starting 8th tradition

### ISSUE THREAD

**Issue by SamP440** [OriginalTrinity/More-Ascension-Perk-Slots#11]
When choosing the eighth tradition, the game will crash. Having changed my mod set, I found it crashed when UI Overhaul Dynamic.

**Comment by Supremequesopizza** [comment]
This is because they both modify the UI. I funnily enough just ran into this myself. Easy work around is to put this below the UI overhaul. You don't get Dynamic's sleek looking setup, but this one isn't too shabby looking either so no real loss.
