### ISSUE TITLE
Can't select traditions 

### ISSUE THREAD

**Issue by Zousuikakka** [OriginalTrinity/More-Ascension-Perk-Slots#13]
![20230129125751_1](https://user-images.githubusercontent.com/43299334/215304256-d26f07da-42db-449e-acfe-bec6482a82de.jpg)

As you see, some traditions are out of the screen, so we can't choose it.

Using MOD: This mod only
Resolution:1920*1080 (Borderless Window)
UI scaling: 1.0
Language:English (Japanese, too)

And, I translated texts of this mod in Japanese. I am glad if  you take it in the mod.
[mas_l_japanese.zip](https://github.com/OriginalTrinity/More-Ascension-Perk-Slots/files/10528968/mas_l_japanese.zip)

**Comment by OriginalTrinity** [comment]
Should be fixed now.
Also thanks for contributing, your translation has been added :)
